FROM docker.io/golang:1-alpine AS builder
WORKDIR /src
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -trimpath -o /cabetool ./cmd/cabetool

FROM busybox:1.37-glibc
COPY --from=builder /cabetool /usr/local/bin/cabetool
ENTRYPOINT ["sleep", "infinity"]
